name: GitHub Action

on:
  push:
    branches: [ main ]

jobs:
  run-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        working-directory: github_action
        run: cargo build --release
      - name: Run
        run: github_action/target/release/github_action
      - name: Commit and push changes
        run: git config user.name "github-actions" && git config user.email "github-actions@github.com" && git add . && git commit -m "Automated changes from Rust binary" || echo "No changes to commit" && git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
